spring.datasource.url=jdbc:postgresql://localhost:5432/the_third_license_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
logging.level.org.springframework.web=DEBUG

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=OLjRSTbPVxhtiY9XQw542835XaYmpvv5jWmlmwoNcxM=
security.jwt.expiration-ms=900000  # 15 minutes
security.jwt.refresh-expiration-ms=604800000 

logging.level.root=DEBUG
logging.level.org.apache.coyote.http11=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

app.currency-exchange-rate=1.25


stripe.secret.key=sk_test_YOUR_STRIPE_SECRET_KEY



